<?php

namespace Bemoove\AppBundle\Repository\Place;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray() {
        $list = $this->findAll();
        $res = array();
        foreach($list as $city) {
            $res[$city->getId()] = $city->getName();
        }
        return $res;
    }
}