Bemoove\AppBundle\Entity\Account:
    collectionOperations:
        post:
          method: 'POST'
    itemOperations:
        get:
            method: 'GET'
            access_control: "is_granted('IS_AUTHENTICATED_FULLY') and object == user"
            access_control_message: "Sorry, but you are not the business owner."
    properties:
      business:
        subresource:
          resourceClass: 'Bemoove\AppBundle\Entity\Business'
          collection: false
          access_control: "is_granted('ROLE_PARTNER') and object.getOwner() == user"
          access_control_message: "Sorry, but you are not the business owner."

Bemoove\AppBundle\Entity\Place\Address:
    collectionOperations:
        getMyWorkoutAddress:
            route_name: 'getMyWorkoutAddress'
        post:
            method: 'POST'
        get:
            method: 'GET'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\BankAccount:
    collectionOperations:
        getMyBankAccount:
            route_name: 'getMyBankAccount'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\BillingMandate:
    collectionOperations:
        checkBillingMandate:
            route_name: 'checkBillingMandate'
        signBillingMandate:
            route_name: 'signBillingMandate'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\Business:
    collectionOperations:
          get:
            method: 'GET'
    #     getMyBusiness:
    #         route_name: 'getMyBusiness'
    itemOperations:
        get:
            method: 'GET'
            access_control: "is_granted('ROLE_PARTNER') and object.getOwner() == user"
            access_control_message: "Sorry, but you are not the business owner."
        put:
            method: 'PUT'
            access_control: "is_granted('ROLE_PARTNER') and object.getOwner() == user"

Bemoove\AppBundle\Entity\Coach:
    collectionOperations:
        getMyCoaches:
            route_name: 'getMyCoaches'
        post:
            method: 'POST'

OrderBundle\Entity\Cart:
    collectionOperations:
        post:
            method: 'POST'
        getMyCurrentCart:
            route_name: 'getMyCurrentCart'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\ForgottenPasswordToken:
    collectionOperations:
        sendForgottenPasswordToken:
            route_name: 'sendForgottenPasswordToken'
        changeForgottenPassword:
            route_name: 'changeForgottenPassword'

OrderBundle\Entity\Order:
    collectionOperations:
        createOrderFromCart:
            route_name: 'createOrderFromCart'
    itemOperations:
        checkOrderPayment:
            route_name: 'checkOrderPayment'
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\Person:
    collectionOperations:
        getMyPerson:
            route_name: 'getMyPerson'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'

Bemoove\AppBundle\Entity\Reservation:
    collectionOperations:
        getMyReservations:
            route_name: 'getMyReservations'
        get:
            method: 'GET'
        post:
            method: 'POST'
    itemOperations:
        get:
            method: 'GET'

Bemoove\AppBundle\Entity\RegistrationToken:
    collectionOperations:
        get:
            method: 'GET'
        post:
            method: 'POST'

Bemoove\AppBundle\Entity\Workout:
    collectionOperations:
        getMyWorkouts:
            route_name: 'getMyWorkouts'
        get:
            method: 'GET'
        post:
            method: 'POST'

Bemoove\AppBundle\Entity\WorkoutInstance:
    collectionOperations:
        getBookableWorkoutInstance:
            route_name: 'getBookableWorkoutInstance'
        get:
            method: 'GET'
        post:
            method: 'POST'
