# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    # configure filters
    address.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'address.search' }]
    bankaccount.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'bankaccount.search' }]
    business.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'business.search' }]
    coach.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { business.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'coach.search' }]
    workout.coach_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { coach.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workout.coach' }]
    workout.owner_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workout.owner' }]
    workout.startdate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { startdate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workout.startdate' }]
    workout.enddate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { enddate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workout.enddate' }]
    workoutinstance.workout_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { workout.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workoutinstance.workout' }]
    workoutinstance.coach_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { coach.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workoutinstance.coach' }]
    workoutinstance.startdate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { startdate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workoutinstance.startdate' }]
    workoutinstance.enddate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { enddate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workoutinstance.enddate' }]
    sport.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'partial' }]
        tags: [ { name: 'api_platform.filter', id: 'sport.search' }]
