parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     bemoove_behat
    database_user:     root
    database_password: 9mft32h7
    cors_allow_origin: 'http://localhost'
    jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    jwt_public_key_path: '%kernel.root_dir%/../var/jwt/public.pem'
    jwt_key_pass_phrase: thisispassphrase
    jwt_token_ttl: 3600
