api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@BemooveAppBundle/EventSubscriber/'
    type:     'annotation'

bemoove_user:
    resource: "@BemooveUserBundle/Resources/config/routing.yml"
    prefix:   /
