api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@BemooveAppBundle/EventSubscriber/'
    type:     'annotation'

bemoove_user:
    resource: "@BemooveUserBundle/Resources/config/routing.yml"
    prefix:   /

bemoove_appbundle:
    resource: "@BemooveAppBundle/Resources/config/routing.yml"
    prefix:   /

order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /

check_Billing_Mandate:
    resource: "@BemooveAppBundle/Action/CheckBillingMandate.php"
    prefix:   /
    type:     annotation

sign_Billing_Mandate:
    resource: "@BemooveAppBundle/Action/SignBillingMandate.php"
    prefix:   /
    type:     annotation

send_forgotten_password_token:
    resource: "@BemooveAppBundle/Action/SendForgottenPasswordToken.php"
    prefix:   /
    type:     annotation

change_forgotten_password:
    resource: "@BemooveAppBundle/Action/ChangeForgottenPassword.php"
    prefix:   /
    type:     annotation
