# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        bemoove_sporty_account_provider:
            id: api.bemoove.account.provider

    encoders:
        Bemoove\AppBundle\Entity\Account:
            algorithm: sha512
            iterations: 8666
            encode_as_base64: true

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PARTNER: ROLE_PARTNER
        ROLE_ADMIN: ROLE_ADMIN

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: bemoove_sporty_account_provider
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        notsecure:
            pattern: ^/images
            security: false

        notsecure2:
            pattern: ^/accounts
            methods: [POST]
            security: false

        notsecure3:
            pattern: ^/registration_tokens
            methods: [POST]
            security: false

        notsecure4:
            pattern: ^/carts
            methods: [POST]
            security: false

        notsecure5:
            pattern: ^/send_forgotten_password_token
            methods: [POST]
            security: false

        notsecure6:
            pattern: ^/change_forgotten_password
            methods: [POST]
            security: false

        main:
            pattern:   ^/
            methods: [POST, PUT]
            provider: bemoove_sporty_account_provider
            stateless: true
            # lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main22:
            pattern:   ^/getMy
            methods: [GET]
            provider: bemoove_sporty_account_provider
            stateless: true
            # lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main23:
            pattern:   ^/checkBillingMandate
            methods: [GET]
            provider: bemoove_sporty_account_provider
            stateless: true
            # lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main24:
            pattern:   ^/signBillingMandate
            methods: [GET]
            provider: bemoove_sporty_account_provider
            stateless: true
            # lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addresses, roles: [ ROLE_PARTNER, ROLE_USER ], methods: [POST, PUT] }
        # - { path: ^/addresses, roles: IS_AUTHENTICATED_ANONYMOUSLY }
