# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        bemoove_sporty_user_provider:
            id: api.bemoove.user.provider

    encoders:
        Bemoove\AppBundle\Entity\User:
            algorithm: sha512
            iterations: 8666
            encode_as_base64: true

    role_hierarchy:
        ROLE_COACH: ROLE_COACH
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: bemoove_sporty_user_provider
            form_login:
                check_path: /login_check
                username_parameter: email
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        notsecure:
            pattern: ^/images
            security: false

        main:
            pattern:   ^/
            methods: [POST, PUT]
            provider: bemoove_sporty_user_provider
            stateless: true
            anonymous: true
            lexik_jwt: ~
            # guard:
            #     authenticators:
            #         - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/addresses, roles: [ ROLE_COACH ], methods: [POST, PUT] }
        - { path: ^/addresses, roles: IS_AUTHENTICATED_ANONYMOUSLY }
