# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.bemoove.user.provider:
        class: Bemoove\UserBundle\Services\BemooveSportyUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    api.event.jwt_created_listener:
        class: Bemoove\UserBundle\Services\JWTCreatedListener
        arguments: [ '@request_stack', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    workout.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { coach.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workout.search' }]
    address.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { user.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'address.search' }]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
