# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.bemoove.account.provider:
        class: Bemoove\UserBundle\Services\BemooveSportyUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    api.event.jwt_created_listener:
        class: Bemoove\UserBundle\Services\JWTCreatedListener
        arguments: [ '@request_stack', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    api.event.jwt_expired_listener:
        class: Bemoove\AppBundle\EventListener\JWTExpiredListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
    api.event.jwt_invalid_listener:
        class: Bemoove\UserBundle\Services\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
    api.event.jwt_notfound_listener:
        class: Bemoove\UserBundle\Services\JWTNotFoundListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }


    address.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { creator.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'address.search' }]
    bankaccount.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'bankaccount.search' }]
    business.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'business.search' }]
    workout.coach_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { coach.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'workout.coach' }]
    workout.startdate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { startdate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workout.startdate' }]
    workout.enddate_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { enddate: ~ }]
        tags: [ { name: 'api_platform.filter', id: 'workout.enddate' }]
    profile.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner.id: 'exact' }]
        tags: [ { name: 'api_platform.filter', id: 'profile.search' }]
    sport.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'partial' }]
        tags: [ { name: 'api_platform.filter', id: 'sport.search' }]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
