# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
       # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    mymail:
        class: Bemoove\AppBundle\Services\MyMail
        public: true
        arguments:
            $environment: '%kernel.environment%'
            $client_front_url: '%client_front_url%'

    Bemoove\AppBundle\EventSubscriber\:
        resource: '../../src/Bemoove/AppBundle/EventSubscriber'

    Bemoove\AppBundle\Action\:
        resource: '../../src/Bemoove/AppBundle/Action'
        public: true
        tags: ['controller.service_arguments']

    api.bemoove.account.provider:
        class: Bemoove\UserBundle\Services\BemooveSportyUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    api.event.jwt_created_listener:
        class: Bemoove\UserBundle\Services\JWTCreatedListener
        arguments: [ '@request_stack', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    api.event.jwt_expired_listener:
        class: Bemoove\AppBundle\EventListener\JWTExpiredListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
    api.event.jwt_invalid_listener:
        class: Bemoove\UserBundle\Services\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
    api.event.jwt_notfound_listener:
        class: Bemoove\UserBundle\Services\JWTNotFoundListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
