<?php

namespace OrderBundle\Repository;

use Bemoove\AppBundle\Entity\Member;
/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
  public function findCurrentCart(string $ip = '', $member = null) {
    $qb = $this->createQueryBuilder('a');

    if($member !== null) {
      $qb
        ->innerjoin('a.member', 'm')
        ->addSelect('m');
      $qb->andwhere('a.member = :member')
         ->setParameter('member', $member->getId());
    }

    $ip_pattern = "/^\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/";
    if(preg_match($ip_pattern, $ip)) {
      $qb->andwhere('a.originIp = :ip')
         ->setParameter('ip', $ip);
    }

    $halfHourAgo = new \Datetime('30 minutes ago');
    $qb->andwhere('a.dateAdd > :halfhourago')
       ->setParameter('halfhourago', $halfHourAgo);

    $qb->orderBy('a.dateAdd', 'DESC');
    $qb->setMaxResults(1);

    return $qb->getQuery()
              ->getOneOrNullResult();
  }

}
