<?php

namespace Bemoove\AppBundle\Repository;

/**
 * ForgottenPasswordTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForgottenPasswordTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
