<?php

namespace Bemoove\AppBundle\Repository;

/**
 * MailChangeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailChangeRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
