<?php

namespace Bemoove\AppBundle\Repository;

/**
 * PartnerAccountValidationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerAccountValidationRepository extends \Doctrine\ORM\EntityRepository
{
}
