<?php

namespace Bemoove\AppBundle\Repository;

/**
 * RegistrationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
