<?php

namespace Bemoove\AppBundle\Repository;

/**
 * ReservationStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationStateRepository extends \Doctrine\ORM\EntityRepository
{
}
