<?php

namespace Bemoove\AppBundle\Repository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindAllAsArray() {
        $list = $this->findAll();
        $res = array();
        foreach($list as $sport) {
            $res[$sport->getId()] = $sport->getName();
        }
        return $res;
    }
}
