<?php

namespace Bemoove\AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

// N'oubliez pas ce use

use Doctrine\ORM\QueryBuilder;

/**
 * WorkoutInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutInstanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBookableByWorkout($id_workout) {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.workout = :workout')
            ->setParameter('workout', $id_workout)
            ->andWhere('a.soldOut = 0')
            ;

        $this->whereBookable($qb);

        $qb->orderBy('a.startdate', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function whereBookable(QueryBuilder $qb) {
        $qb
            ->andWhere('a.startdate > :start')
            ->setParameter('start', new \DateTime('tomorrow'));
    }
}
