<?php

namespace Bemoove\AppBundle\Repository;

/**
 * TrainingSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByCityId($city) {
        if(!is_array($city)) {
            $city = array($city);
        }
        $qb = $this->createQueryBuilder('a')
                            ->join('a.address', 'address')
                            ->join('address.city', 'city')
                            ->andWhere('city.id IN (:ids)')
                            ->setParameter('ids', $city)
                            ->addSelect('address');
        return $qb->getQuery()->getResult();
    }
}
