<?php

namespace Bemoove\AppBundle\Repository;

/**
 * WorkoutInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
