# bemoove_front:
#     resource: "@BemooveAppBundle/Resources/config/routing-front.yml"
#     prefix:   /
#
# bemoove_app_coach_profile:
#     path:     /profile
#     defaults: { _controller: BemooveAppBundle:Coach:profile }
