# getMyBusiness:
#     path: /getMyBusiness/
#     methods: ['GET']
#     defaults:
#         _controller: 'BemooveAppBundle:ACtion:GetMyBusiness'
#         _api_resource_class: 'Bemoove\AppBundle\Entity\Business'
#         _api_collection_operation_name: 'BemooveAppBundle:getMyBusiness'
