bemoove_app_homepage:
    path:     /
    defaults: { _controller: BemooveAppBundle:Default:index }

bemoove_user_register:
    path:     /user-register
    defaults: { _controller: BemooveAppBundle:Default:register }

bemoove_user_register_with_profile:
    path:     /user-register-full
    defaults: { _controller: BemooveAppBundle:Default:registerfull }

bemoove_app_list_training:
    path:     /list
    defaults: { _controller: BemooveAppBundle:Search:list }

bemoove_app_search_result:
    path:     /search
    defaults: { _controller: BemooveAppBundle:Search:result }

bemoove_app_search_viewtraining:
    path:     /trainingsession/{idtrainingsession}
    defaults: { _controller: BemooveAppBundle:Search:viewtraining }
    requirements:
        idtrainingsession:  \d+

bemoove_app_display_profile:
    path:   /profile/{iduser}
    defaults:   { _controller: BemooveAppBundle:Profile:display}
    requirements:
        iduser:  \d+