get_my_business:
    resource: "@BemooveAppBundle/Action/GetMyBusiness.php"
    prefix:   /
    type:     annotation

get_my_workouts:
    resource: "@BemooveAppBundle/Action/GetMyWorkouts.php"
    prefix:   /
    type:     annotation

get_my_coaches:
    resource: "@BemooveAppBundle/Action/GetMyCoaches.php"
    prefix:   /
    type:     annotation

get_my_bank_account:
    resource: "@BemooveAppBundle/Action/GetMyBankAccount.php"
    prefix:   /
    type:     annotation

get_my_workout_address:
    resource: "@BemooveAppBundle/Action/GetMyWorkoutAddress.php"
    prefix:   /
    type:     annotation

get_bookable_workout_instance:
    resource: "@BemooveAppBundle/Action/GetBookableWorkoutInstance.php"
    prefix:   /
    type:     annotation

get_my_person:
    resource: "@BemooveAppBundle/Action/GetMyPerson.php"
    prefix:   /
    type:     annotation

get_my_reservations:
    resource: "@BemooveAppBundle/Action/GetMyReservations.php"
    prefix:   /
    type:     annotation

cancel_reservation:
    resource: "@BemooveAppBundle/Action/CancelReservation.php"
    prefix:   /
    type:     annotation
