bemoove_front:
    resource: "@BemooveAppBundle/Resources/config/routing-front.yml"
    prefix:   /

bemoove_sporty:
    resource: "@BemooveAppBundle/Resources/config/routing-sporty.yml"
    prefix:   /sporty

bemoove_coach:
    resource: "@BemooveAppBundle/Resources/config/routing-coach.yml"
    prefix:   /coach